feat: cs 43 06 get coverage
SoftDevSix/ArgosApplication pull request #5
Opened 2024-11-22 05:14 UTC by ronaldo-mendoza-jalafund

## Related Tickets & US
- [item title]()

## Description

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have checked my code and corrected any misspellings

2024-11-25 11:46 UTC, 0santisimo0 commented
![image](https://github.com/user-attachments/assets/ac37d8d6-b31c-4be6-a3a4-8929195c9f1c)
Why are there 2 "dtos" directories, sort the project, remove non-useful classes

2024-11-25 12:43 UTC, 0santisimo0 requested changes
![image (19)](https://github.com/user-attachments/assets/5d2d97b6-5dc3-4022-a0d0-a52d382e6fb6)
[Duplicated classes and code, order the project erase un-useful classes]

2024-11-25 12:43 UTC, 0santisimo0 commented on src/main/java/com/softdevsix/domain/enums/Status.java
> +public enum Status {
Empty enum Class, Use CoverageStatus enum class that has the 3 status types

2024-11-25 12:43 UTC, 0santisimo0 commented on src/main/java/com/softdevsix/domain/files/enums/IssueType.java
> +public enum IssueType {
This enum already exists in another directory, and this enum isn't complete, erase this class

2024-11-25 12:43 UTC, 0santisimo0 commented on src/main/java/com/softdevsix/domain/files/enums/Severity.java
> +public enum Severity {
This enum already exists in another directory, and this enum isn't complete, erase this class

2024-11-25 12:43 UTC, 0santisimo0 commented on src/main/java/com/softdevsix/domain/pullrequests/PullRequest.java
> +public class PullRequest {
Empty entity, pull request will no longer be used, please check the new workflow. Information will not be received from a pull request now it is received from a static loading project.

2024-11-25 12:43 UTC, 0santisimo0 commented on src/main/java/com/softdevsix/domain/pullrequests/PullRequestCoverage.java
> +public class PullRequestCoverage {
Erase pullRequests Directory, non-useful Classes, this entities already exist

2024-11-25 12:46 UTC, 0santisimo0 commented
![image](https://github.com/user-attachments/assets/768fcb81-afff-4aeb-b755-8721797f94d8)
Why Project, Issue, Coverage, FileCoverage or Project and enums are inside package "files" ?

2024-11-29 19:07 UTC, GabyGV-GGV commented
Why is this pull request being closed?
@zamoranoalicia  Because this was a base implementation with the previous entities, an update was being performed, and due to time issues, it was done in another branch with the same idea of ​​the business logic, but with the updated entities.
Owner: @ronaldo-mendoza-jalafund 
Reviews: @0santisimo0

2024-11-29 19:07 UTC, closed without merging